### ISSUE TITLE
difference between Allow and Session ?

### ISSUE THREAD

**Issue by laozi83** [vrillusions/permit-cookies#30]
Good evening
I use with great satisfaction Permit Cookies 2,
but I do not understand the difference between Allow and Session
When I select 'Session', the cookie persists in history after close FireFox 42.0!
only the words "allow for session" appears in the history
lighting
Thank you
Windows 7 édition familiale 32 bits

**Comment by vrillusions** [comment]
Apologies on just getting to this now.

Permit cookies works best when you go to options > Privacy and set the following:

![firefox options](https://cloud.githubusercontent.com/assets/53131/12665956/01cc4878-c60a-11e5-8102-1d80ab37f12f.PNG)

Note you will likely have to go to `Show Cookies...` and remove all the cookies you don't want.  This may have been fixed now but at one point it would only clear out new cookies not the existing ones.  With that option set the 4 values and their meaning:

* `Allow` Adds site to exceptions with a status of `Allow`. This is typically the only one you'll use.
* `Session` Adds site to exceptions with a status of `Allow for session`.  Since the option set above is to keep cookies until `I close Firefox` there's really no reason to use this.  In other setups where you keep cookies until `They expire` you can use the `Session` option to say the cookies for this site should not persist between restarts (again, you may have to delete existing cookies, I haven't tested this)
* `Block` Adds site to exceptions with a status of `Block`. No cookies will ever be set for this host
* `Remove` Removes the site from exceptions. Note it does not delete the actual cookies, just the exception

Using the above setup the number of cookies I have saved in firefox to less than 20.  Everything else is deleted the next time I start Firefox.  This has the nice side effect that all those tracking cookies that exist now won't persist between restarts of Firefox.

Let me know if you have any other questions.
